version: '3.9'

services:
  backend:           #name services
    build: .         #build setup 
    container_name: backend 
    command: python manage.py runserver 0.0.0.0:8000         #run command
    volumes:            #Put the changes of folder 'core' in the 'app' file ((link them))
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test             
      - DEBUG=True


# (line 12-14) : SECRET_KEY and DEBUG environment editable in settings.py django

  
# COMMAND:
# docker-compose up --build                                                             up Docker-Compose along with 'build' file (line 5)
# docker-compose logs -f                                                                show logs
# docker-compose exec backend sh -c 'pip install python-decouple'                       install python-decouple package in container_name services (backend)
                                                                                        # notics: first you are build again docker-compose because python-decouple package
                                                                                        #         not building in docker (explain in next line)
# docker compose up --build -d                                                                                        

# others:
# python-decouple package python                             link between environment and django applications