version: '3.9'

services:

  redis:
    container_name: redis
    image: redis
    restart: always    
    ports:
     - "6379:6379"   
    command: redis-server --save 60 1 --loglevel warning 


  backend:           #name services
    build: .         #build setup 
    container_name: backend 
    command: gunicorn core.wsgi --bind 0.0.0.0:8000      #run command
    volumes:            #Put the changes of folder 'core' in the 'app' file ((link them))
      - ./core:/app
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test             
      - DEBUG=False
    depends_on:
      - redis

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - redis
      - backend
    

  worker:
    build: .
    command: celery -A core worker -loglevel=info
    depends_on:
      - redis
      - backend