name: django project test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose
    - run: docker-compose up -d
    - name: run tests
    -  un: docker exec backend sh -c 'flake8 & pytest .'
